print("Ola Mundo!")
print("Caboclo")
print("Legião Urbana")
print("")
print("Não tinha medo o tal João de Santo Cristo")
print("Era o que todos diziam quando ele se perdeu")
print("Deixou pra trás todo o marasmo da fazenda")
print("Só pra sentir no seu sangue o ódio que Jesus lhe deu")
print("Quando criança, só pensava em ser bandido")
print("Ainda mais quando com um tiro de soldado o pai morreu")
print("Era o terror da sertania onde morava")
print("E na escola até o professor com ele aprendeu")
print("")
print("Ia pra igreja só pra roubar o dinheiro")
print("Que as velhinhas colocavam na caixinha do altar")
print("Sentia mesmo que era mesmo diferente")
print("Sentia que aquilo ali não era o seu lugar")
print("Ele queria sair para ver o mar")
print("E as coisas que ele via na televisão")
print("Juntou dinheiro para poder viajar")
print("De escolha própria, escolheu a solidão")
print("")
print("Comia todas as menininhas da cidade")
print("De tanto brincar de médico, aos doze, era professor")
print("Aos quinze, foi mandado pro reformatório")
print("Onde aumentou seu ódio diante de tanto terror")
print("Não entendia como a vida funcionava")
print("Discriminação por causa da sua classe e sua cor")
print("Ficou cansado de tentar achar resposta")
print("E comprou uma passagem, foi direto a Salvador")
print("")
print("E lá chegando, foi tomar um cafezinho")
print("E encontrou um boiadeiro com quem foi falar")
print("E o boiadeiro tinha uma passagem e ia perder a viagem")
print("Mas João foi lhe salvar")
print("Dizia ele: Estou indo pra Brasília")
print("Neste país lugar melhor não há")
print("Tô precisando visitar a minha filha")
print("Eu fico aqui e você vai no meu lugar")
print("")
print("E João aceitou sua proposta")
print("E num ônibus entrou no Planalto Central")
print("Ele ficou bestificado com a cidade")
print("Saindo da rodoviária, viu as luzes de Natal")
print("Meu Deus, mas que cidade linda")
print("No Ano Novo eu começo a trabalhar")
print("Cortar madeira, aprendiz de carpinteiro")
print("Ganhava cem mil por mês em Taguatinga")
print("")
print("Na sexta-feira, ia pra zona da cidade")
print("Gastar todo o seu dinheiro de rapaz trabalhador")
print("E conhecia muita gente interessante")
print("Até um neto bastardo do seu bisavô")
print("Um peruano que vivia na Bolívia")
print("E muitas coisas trazia de lá")
print("Seu nome era Pablo e ele dizia")
print("Que um negócio ele ia começar")
print("")
print("E Santo Cristo até a morte trabalhava")
print("Mas o dinheiro não dava pra ele se alimentar")
print("E ouvia às sete horas o noticiário")
print("Que sempre dizia que o seu ministro ia ajudar")
print("Mas ele não queria mais conversa")
print("E decidiu que, como Pablo, ele iria se virar")
print("Elaborou mais uma vez seu plano santo")
print("E, sem ser crucificado, a plantação foi começar")
print("")
print("Logo, logo os malucos da cidade souberam da novidade")
print("Tem bagulho bom aí")
print("E João de Santo Cristo ficou rico")
print("E acabou com todos os traficantes dali")
print("Fez amigos, frequentava a Asa Norte")
print("E ia pra festa de rock pra se libertar")
print("")
print("Mas de repente, sob uma má influência")
print("Dos boyzinhos da cidade, começou a roubar")
print("Já no primeiro roubo ele dançou")
print("E pro inferno ele foi pela primeira vez")
print("Violência e estupro do seu corpo")
print("Vocês vão ver, eu vou pegar vocês")
print("")
print("Agora o Santo Cristo era bandido")
print("Destemido e temido no Distrito Federal")
print("Não tinha nenhum medo de polícia")
print("Capitão ou traficante, playboy ou general")
print("Foi quando conheceu uma menina")
print("E de todos os seus pecados ele se arrependeu")
print("Maria Lúcia era uma menina linda")
print("E o coração dele pra ela o Santo Cristo prometeu")
print("")
print("Ele dizia que queria se casar")
print("E carpinteiro ele voltou a ser")
print("Maria Lúcia, pra sempre vou te amar")
print("E um filho com você eu quero ter")
print("")
print("O tempo passa e um dia vem na porta")
print("Um senhor de alta classe com dinheiro na mão")
print("E ele faz uma proposta indecorosa")
print("E diz que espera uma resposta")
print("Uma resposta do João")
print("Não boto bomba em banca de jornal")
print("Nem em colégio de criança, isso eu não faço, não")
print("E não protejo general de dez estrelas")
print("Que fica atrás da mesa com o cu na mão")
print("E é melhor o senhor sair da minha casa")
print("Nunca brinque com um Peixes de ascendente Escorpião")
print("Mas antes de sair, com ódio no olhar, o velho disse")
print("Você perdeu sua vida, meu irmão")
print("")
print("Você perdeu a sua vida, meu irmão")
print("Você perdeu a sua vida, meu irmão")
print("Essas palavras vão entrar no coração")
print("Eu vou sofrer as consequências como um cão")
print("")
print("Não é que o Santo Cristo estava certo?")
print("Seu futuro era incerto e ele não foi trabalhar")
print("Se embebedou e no meio da bebedeira")
print("Descobriu que tinha outro trabalhando em seu lugar")
print("Falou com Pablo que queria um parceiro")
print("E também tinha dinheiro e queria se armar")
print("Pablo trazia o contrabando da Bolívia")
print("E Santo Cristo revendia em Planaltina")
print("")
print("Mas acontece que um tal de Jeremias")
print("Traficante de renome, apareceu por lá")
print("Ficou sabendo dos planos de Santo Cristo")
print("E decidiu que com João ele ia acabar")
print("Mas Pablo trouxe uma Winchester 22")
print("E Santo Cristo já sabia atirar")
print("E decidiu usar a arma só depois")
print("Que Jeremias começasse a brigar")
print("")
print("Jeremias, maconheiro sem-vergonha")
print("Organizou a Rockonha e fez todo mundo dançar")
print("Desvirginava mocinhas inocentes")
print("Se dizia que era crente, mas não sabia rezar")
print("E Santo Cristo há muito não ia pra casa")
print("E a saudade começou a apertar")
print("Eu vou-me embora, eu vou ver Maria Lúcia")
print("Já tá em tempo de a gente se casar")
print("")
print("Chegando em casa, então, ele chorou")
print("E pro inferno ele foi pela segunda vez")
print("Com Maria Lúcia, Jeremias se casou")
print("E um filho nela ele fez")
print("")
print("Santo Cristo era só ódio por dentro")
print("E então o Jeremias pra um duelo ele chamou")
print("Amanhã, às duas horas, na Ceilândia")
print("Em frente ao lote catorze, e é pra lá que eu vou")
print("E você pode escolher as suas armas")
print("Que eu acabo mesmo com você, seu porco traidor")
print("E mato também Maria Lúcia")
print("Aquela menina falsa pra quem jurei o meu amor")
print("")
print("E o Santo Cristo não sabia o que fazer")
print("Quando viu o repórter da televisão")
print("Que deu notícia do duelo na TV")
print("Dizendo a hora, e o local e a razão")
print("")
print("No sábado, então, às duas horas")
print("Todo o povo, sem demora, foi lá só para assistir")
print("Um homem que atirava pelas costas")
print("E acertou o Santo Cristo e começou a sorrir")
print("Sentindo o sangue na garganta")
print("João olhou pras bandeirinhas e pro povo a aplaudir")
print("E olhou pro sorveteiro e pras câmeras")
print("E a gente da TV que filmava tudo ali")
print("")
print("E se lembrou de quando era uma criança")
print("E de tudo o que vivera até ali")
print("E decidiu entrar de vez naquela dança")
print("Se a Via-Crúcis virou circo, estou aqui")
print("")
print("E nisso, o Sol cegou seus olhos")
print("E então Maria Lúcia ele reconheceu")
print("Ela trazia a Winchester 22")
print("A arma que seu primo Pablo lhe deu")
print("")
print("Jeremias, eu sou homem, coisa que você não é")
print("E não atiro pelas costas, não")
print("Olha pra cá, filha da puta sem-vergonha")
print("Dá uma olhada no meu sangue e vem sentir o teu perdão")
print("E Santo Cristo, com a Winchester 22")
print("Deu cinco tiros no bandido traidor")
print("Maria Lúcia se arrependeu depois")
print("E morreu junto com João, seu protetor")
print("")
print("O povo declarava que João de Santo Cristo")
print("Era santo porque sabia morrer")
print("E a alta burguesia da cidade")
print("Não acreditou na história que eles viram na TV")
print("E João não conseguiu o que queria")
print("Quando veio pra Brasília com o diabo ter")
print("Ele queria era falar pro presidente")
print("Pra ajudar toda essa gente que só faz")
print("")
print("Sofrer")